# Generated by Django 4.2.11 on 2025-03-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(max_length=255, verbose_name='Descricao'),
        ),
    ]
