# Generated by Django 4.2.11 on 2025-03-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0002_alter_denuncia_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='celular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular'),
        ),
    ]
