# Generated by Django 4.2.11 on 2025-03-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_alter_denuncia_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='status_denuncia',
            field=models.CharField(choices=[('analysis', 'Em análise'), ('archived', 'Arquivada'), ('completed', 'Concluída')], max_length=10, verbose_name='Status'),
        ),
    ]
